name: Deploy Static Resume to AWS EC2

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:  # Allows manual triggering from UI

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  APP_NAME: "static-resume"
  APP_FOLDER: "static-resume-main"

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Check Workflow Trigger
      run: |
        echo "GITHUB_REF: $GITHUB_REF"
        echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
        echo "Repository contents:"
        ls -la
        echo "App folder contents:"
        ls -la ${{ env.APP_FOLDER }}
        
  build:
    name: Build Static Site
    needs: debug
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: ${{ env.APP_FOLDER }}
    
    - name: Verify Node.js
      working-directory: ./${{ env.APP_FOLDER }}
      run: |
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "Package contents:"
        ls -la
    
    # Rest of your existing build steps...