name: Deploy Static Resume to AWS EC2

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  DEPLOY_DIR: "/var/www/html"
  TEMP_DIR: "/tmp/static-resume"

jobs:
  build:
    name: Package Site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: site-build
          path: ./

  deploy-dev:
    name: Deploy to Development
    needs: build
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: site-build
          path: build/

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Files
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" build/ ec2-user@${{ secrets.DEV_SERVER_IP }}:${{ env.TEMP_DIR }}/
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.DEV_SERVER_IP }} <<'EOF'
            set -ex
            sudo dnf install -y httpd || true
            sudo systemctl stop httpd || true
            sudo fuser -k 80/tcp || true
            sudo rm -rf $DEPLOY_DIR/*
            sudo mkdir -p $DEPLOY_DIR
            sudo cp -r $TEMP_DIR/* $DEPLOY_DIR/
            sudo chown -R apache:apache $DEPLOY_DIR
            sudo chmod -R 755 $DEPLOY_DIR
            sudo restorecon -Rv $DEPLOY_DIR || true
            sudo systemctl start httpd
            echo "Dev deployment successful"
          EOF

  deploy-prod:
    name: Deploy to Production
    needs: deploy-dev
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: site-build
          path: build/

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Files
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" build/ ec2-user@${{ secrets.PROD_SERVER_IP }}:${{ env.TEMP_DIR }}/
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.PROD_SERVER_IP }} <<'EOF'
            set -ex
            sudo dnf install -y httpd || true
            sudo systemctl stop httpd || true
            sudo fuser -k 80/tcp || true
            sudo rm -rf $DEPLOY_DIR/*
            sudo mkdir -p $DEPLOY_DIR
            sudo cp -r $TEMP_DIR/* $DEPLOY_DIR/
            sudo chown -R apache:apache $DEPLOY_DIR
            sudo chmod -R 755 $DEPLOY_DIR
            sudo restorecon -Rv $DEPLOY_DIR || true
            sudo systemctl start httpd
            curl -I http://localhost || true
            echo "Production deployment successful"
          EOF