name: Deploy Static Resume to AWS EC2

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/static-resume
  DEV_SERVER: ${{ secrets.DEV_SERVER_IP }}
  PROD_SERVER: ${{ secrets.PROD_SERVER_IP }}

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:latest

  deploy-dev:
    name: Deploy to Development EC2
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Docker container on Dev EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.DEV_SERVER }} << EOF
            docker pull $IMAGE_NAME:latest
            docker stop static-resume || true
            docker rm static-resume || true
            docker run -d --name static-resume -p 80:80 \
              -e ENV=development \
              $IMAGE_NAME:latest
          EOF

  deploy-prod:
    name: Deploy to Production EC2
    needs: deploy-dev
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Docker container on Prod EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ env.PROD_SERVER }} << EOF
            docker pull $IMAGE_NAME:latest
            docker stop static-resume || true
            docker rm static-resume || true
            docker run -d --name static-resume -p 80:80 \
              -e ENV=production \
              $IMAGE_NAME:latest
          EOF
