name: Deploy Static Resume to AWS EC2

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  APP_NAME: "static-resume"
  DEV_SERVER: ${{ secrets.DEV_SERVER_IP }}
  PROD_SERVER: ${{ secrets.PROD_SERVER_IP }}

jobs:
  build:
    name: Prepare Static Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Archive HTML files
        uses: actions/upload-artifact@v4
        with:
          name: static-resume-build
          path: ./  # Adjust if your HTML files are in a subfolder

  deploy-dev:
    name: Deploy to Development
    needs: build
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: static-resume-build
          path: build/

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to Dev EC2
        run: |
          tar -czf static-resume.tar.gz -C build/ .
          scp -o StrictHostKeyChecking=no static-resume.tar.gz ec2-user@${{ env.DEV_SERVER }}:/tmp/
          ssh -o StrictHostKeyChecking=no ec2-user@${{ env.DEV_SERVER }} << 'EOF'
            set -e
            sudo apt update -y
            sudo apt install -y nginx curl
            sudo systemctl enable nginx
            sudo systemctl start nginx

            DEPLOY_DIR="/var/www/static-resume"
            sudo mkdir -p $DEPLOY_DIR
            sudo tar -xzf /tmp/static-resume.tar.gz -C $DEPLOY_DIR
            sudo chown -R nginx:nginx $DEPLOY_DIR
            echo "✅ Dev deployment complete"
          EOF

  deploy-prod:
    name: Deploy to Production
    needs: deploy-dev
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: static-resume-build
          path: build/

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Prod EC2
        run: |
          tar -czf static-resume.tar.gz -C build/ .
          scp -o StrictHostKeyChecking=no static-resume.tar.gz ec2-user@${{ env.PROD_SERVER }}:/tmp/
          ssh -o StrictHostKeyChecking=no ec2-user@${{ env.PROD_SERVER }} << 'EOF'
            set -e
            sudo apt update -y
            sudo apt install -y nginx curl
            sudo systemctl enable nginx
            sudo systemctl start nginx

            DEPLOY_DIR="/var/www/static-resume"
            TIMESTAMP=$(date +%Y%m%d%H%M%S)
            sudo mkdir -p /var/www/backups
            [ -d "$DEPLOY_DIR" ] && sudo tar -czf /var/www/backups/static-resume-$TIMESTAMP.tar.gz -C $DEPLOY_DIR .

            sudo mkdir -p $DEPLOY_DIR
            sudo tar -xzf /tmp/static-resume.tar.gz -C $DEPLOY_DIR
            sudo chown -R nginx:nginx $DEPLOY_DIR
            echo " Prod deployment complete"
          EOF
