# .github/workflows/deploy-html.yml
name: Deploy HTML App to EC2 (Dev & Prod)

on:
  push:
    branches:
      - main

env:
  REMOTE_DIR: /var/www/html

permissions:
  contents: read

jobs:
  deploy-dev:
    name: Deploy to Dev EC2
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Ensure remote dir exists
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.DEV_SERVER_IP }} \
            "sudo mkdir -p $REMOTE_DIR && sudo chown ec2-user:ec2-user $REMOTE_DIR"

      - name: Sync files to Dev
        run: |
          rsync -av --delete \
            --exclude='.github' \
            "$GITHUB_WORKSPACE"/ ec2-user@${{ secrets.DEV_SERVER_IP }}:$REMOTE_DIR/

      - name: Fix perms & restart webserver
        uses: appleboy/ssh-action@master
        with:
          host:     ${{ secrets.DEV_SERVER_IP }}
          username: ec2-user
          key:      ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo chown -R apache:apache $REMOTE_DIR
            sudo chmod -R 755 $REMOTE_DIR
            # Restart whichever service exists
            if systemctl is-active --quiet httpd; then
              sudo systemctl restart httpd
            else
              sudo systemctl restart apache2
            fi

  deploy-prod:
    name: Deploy to Prod EC2
    needs: deploy-dev
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Ensure remote dir exists
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.PROD_SERVER_IP }} \
            "sudo mkdir -p $REMOTE_DIR && sudo chown ec2-user:ec2-user $REMOTE_DIR"

      - name: Sync files to Prod
        run: |
          rsync -av --delete \
            --exclude='.github' \
            "$GITHUB_WORKSPACE"/ ec2-user@${{ secrets.PROD_SERVER_IP }}:$REMOTE_DIR/

      - name: Fix perms & restart webserver
        uses: appleboy/ssh-action@master
        with:
          host:     ${{ secrets.PROD_SERVER_IP }}
          username: ec2-user
          key:      ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo chown -R apache:apache $REMOTE_DIR
            sudo chmod -R 755 $REMOTE_DIR
            if systemctl is-active --quiet httpd; then
              sudo systemctl restart httpd
            else
              sudo systemctl restart apache2
            fi
