name: Deploy to EC2 (Dev & Prod)

on:
  push:
    branches: [ "main" ]

env:
  CONTAINER_NAME: static-resume-container
  APP_PORT: 80
permissions:
  contents: read

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-tag.outputs.tag }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set image tag
      id: set-tag
      run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: 'true'

    - name: Build and push image
      run: |
        docker build -t ${{ steps.login-ecr.outputs.registry }}/static-resume:${{ steps.set-tag.outputs.tag }} .
        docker push ${{ steps.login-ecr.outputs.registry }}/static-resume:${{ steps.set-tag.outputs.tag }}

    - name: Upload deploy script
      uses: actions/upload-artifact@v4
      with:
        name: deploy-script
        path: deploy-container.sh

  deploy-dev:
    name: Deploy to Dev EC2
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: development
    
    steps:
    - name: Download deploy script
      uses: actions/download-artifact@v4
      with:
        name: deploy-script

    - name: Make script executable
      run: chmod +x deploy-container.sh

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Verify Dev Server IP
      run: |
        if [ -z "${{ secrets.DEV_SERVER_IP }}" ]; then
          echo "::error::DEV_SERVER_IP secret is missing"
          exit 1
        fi

    - name: Deploy to Dev EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_SERVER_IP }}
        username: ec2-user
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          echo "=== Starting Dev Deployment ==="
          
          # Login to ECR
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
            sudo docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}
          
          # Execute deployment script
          sudo ./deploy-container.sh \
            "${{ steps.login-ecr.outputs.registry }}/static-resume" \
            "${{ needs.build-and-push.outputs.image_tag }}" \
            "development" \
            "${{ env.APP_PORT }}"

  deploy-prod:
    name: Deploy to Prod EC2
    needs: [build-and-push, deploy-dev]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Download deploy script
      uses: actions/download-artifact@v4
      with:
        name: deploy-script

    - name: Make script executable
      run: chmod +x deploy-container.sh

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Verify Prod Server IP
      run: |
        if [ -z "${{ secrets.PROD_SERVER_IP }}" ]; then
          echo "::error::PROD_SERVER_IP secret is missing"
          exit 1
        fi

    - name: Deploy to Prod EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_SERVER_IP }}
        username: ec2-user
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          echo "=== Starting Prod Deployment ==="
          
          # Login to ECR
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
            sudo docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}
          
          # Execute deployment script
          sudo ./deploy-container.sh \
            "${{ steps.login-ecr.outputs.registry }}/static-resume" \
            "${{ needs.build-and-push.outputs.image_tag }}" \
            "production" \
            "${{ env.APP_PORT }}"