name: Deploy Static Resume to AWS EC2

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  APP_NAME: "static-resume"
  DEV_SERVER: ${{ secrets.DEV_SERVER_IP }}
  PROD_SERVER: ${{ secrets.PROD_SERVER_IP }}

jobs:
  build:
    name: Prepare Static Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Archive HTML files
        uses: actions/upload-artifact@v4
        with:
          name: static-resume-build
          path: ./  # Adjust if your site is in a subfolder

  deploy-dev:
    name: Deploy to Development
    needs: build
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: static-resume-build
          path: build/

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to Dev EC2 and Start Apache
        run: |
          tar -czf static-resume.tar.gz -C build/ .
          scp -o StrictHostKeyChecking=no static-resume.tar.gz ec2-user@${{ env.DEV_SERVER }}:/tmp/
          ssh -o StrictHostKeyChecking=no ec2-user@${{ env.DEV_SERVER }} << 'EOF'
            set -e
            DEPLOY_DIR="/var/www/html"
            sudo mkdir -p $DEPLOY_DIR
            sudo tar -xzf /tmp/static-resume.tar.gz -C $DEPLOY_DIR
            sudo chown -R ec2-user:ec2-user $DEPLOY_DIR

            sudo dnf install -y httpd
            sudo systemctl enable httpd
            sudo systemctl start httpd

            echo " Dev deployment complete and Apache started"
          EOF

  deploy-prod:
    name: Deploy to Production
    needs: deploy-dev
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: static-resume-build
          path: build/

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Prod EC2 and Start Apache
        run: |
          tar -czf static-resume.tar.gz -C build/ .
          scp -o StrictHostKeyChecking=no static-resume.tar.gz ec2-user@${{ env.PROD_SERVER }}:/tmp/
          ssh -o StrictHostKeyChecking=no ec2-user@${{ env.PROD_SERVER }} << 'EOF'
            set -e
            DEPLOY_DIR="/var/www/html"
            sudo mkdir -p $DEPLOY_DIR
            sudo tar -xzf /tmp/static-resume.tar.gz -C $DEPLOY_DIR
            sudo chown -R ec2-user:ec2-user $DEPLOY_DIR

            sudo dnf install -y httpd
            sudo systemctl enable httpd
            sudo systemctl start httpd

            echo "Production deployment complete and Apache started"
          EOF
