name: Deploy Static Resume to AWS EC2

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  APP_NAME: "static-resume"
  DEV_SERVER: ${{ secrets.DEV_SERVER_IP }}
  PROD_SERVER: ${{ secrets.PROD_SERVER_IP }}

jobs:
  build:
    name: Prepare Static Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Archive HTML files
        uses: actions/upload-artifact@v4
        with:
          name: static-resume-build
          path: ./

  deploy-dev:
    name: Deploy to Development
    needs: build
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: static-resume-build
          path: build/

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Dev EC2
        run: |
          tar -czf static-resume.tar.gz -C build/ .
          scp -o StrictHostKeyChecking=no static-resume.tar.gz ec2-user@${{ env.DEV_SERVER }}:/tmp/
          ssh -o StrictHostKeyChecking=no ec2-user@${{ env.DEV_SERVER }} << 'EOF'
            set -ex
            DEPLOY_DIR="/var/www/html"
            
            # Verify/install Apache
            if ! command -v httpd &> /dev/null; then
              sudo dnf install -y httpd
              sudo systemctl enable httpd
            fi
            
            # Stop Apache if running
            sudo systemctl stop httpd || true
            
            # Clean deployment directory
            sudo rm -rf $DEPLOY_DIR/*
            sudo mkdir -p $DEPLOY_DIR
            
            # Extract files
            sudo tar -xzf /tmp/static-resume.tar.gz -C $DEPLOY_DIR
            
            # Set permissions
            sudo chown -R apache:apache $DEPLOY_DIR
            sudo chmod -R 755 $DEPLOY_DIR
            
            # SELinux context
            if command -v sestatus &> /dev/null && sudo sestatus | grep -q "enabled"; then
              sudo restorecon -Rv $DEPLOY_DIR
            fi
            
            # Start Apache with retries
            for i in {1..3}; do
              if sudo systemctl start httpd; then
                echo "Apache started successfully"
                break
              else
                echo "Attempt $i failed, checking logs..."
                sudo journalctl -u httpd --no-pager -n 20
                if [ $i -eq 3 ]; then exit 1; fi
                sleep 5
              fi
            done
            
            echo "Dev deployment complete"
          EOF

  deploy-prod:
    name: Deploy to Production
    needs: deploy-dev
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: static-resume-build
          path: build/

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Prod EC2
        run: |
          tar -czf static-resume.tar.gz -C build/ .
          scp -o StrictHostKeyChecking=no static-resume.tar.gz ec2-user@${{ env.PROD_SERVER }}:/tmp/
          ssh -o StrictHostKeyChecking=no ec2-user@${{ env.PROD_SERVER }} << 'EOF'
            set -ex
            DEPLOY_DIR="/var/www/html"
            
            # Verify/install Apache
            if ! command -v httpd &> /dev/null; then
              sudo dnf install -y httpd
              sudo systemctl enable httpd
            fi
            
            # Stop Apache if running
            sudo systemctl stop httpd || true
            
            # Clean deployment directory
            sudo rm -rf $DEPLOY_DIR/*
            sudo mkdir -p $DEPLOY_DIR
            
            # Extract files
            sudo tar -xzf /tmp/static-resume.tar.gz -C $DEPLOY_DIR
            
            # Set permissions
            sudo chown -R apache:apache $DEPLOY_DIR
            sudo chmod -R 755 $DEPLOY_DIR
            
            # SELinux context
            if command -v sestatus &> /dev/null && sudo sestatus | grep -q "enabled"; then
              sudo restorecon -Rv $DEPLOY_DIR
            fi
            
            # Verify config
            sudo apachectl configtest
            
            # Start Apache with retries
            for i in {1..3}; do
              if sudo systemctl start httpd; then
                echo "Apache started successfully"
                break
              else
                echo "Attempt $i failed, checking logs..."
                sudo journalctl -u httpd --no-pager -n 20
                if [ $i -eq 3 ]; then exit 1; fi
                sleep 5
              fi
            done
            
            # Verify status
            sudo systemctl status httpd --no-pager
            echo "Production deployment complete"
          EOF