name: Deploy Static Resume to AWS EC2

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  APP_NAME: "static-resume"
  DEV_SERVER: ${{ secrets.DEV_SERVER_IP }}
  PROD_SERVER: ${{ secrets.PROD_SERVER_IP }}

jobs:
  build:
    name: Prepare Static Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Archive HTML files
        uses: actions/upload-artifact@v4
        with:
          name: static-resume-build
          path: ./

  deploy-dev:
    name: Deploy to Development
    needs: build
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: static-resume-build
          path: build/

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to Dev EC2
        run: |
          tar -czf static-resume.tar.gz -C build/ .
          scp -o StrictHostKeyChecking=no static-resume.tar.gz ec2-user@${{ env.DEV_SERVER }}:/tmp/
          ssh -o StrictHostKeyChecking=no ec2-user@${{ env.DEV_SERVER }} << 'EOF'
            set -e
            DEPLOY_DIR="/var/www/html"
            
            # Stop Apache before deployment
            sudo systemctl stop httpd || true
            
            # Clean the deployment directory
            sudo rm -rf $DEPLOY_DIR/*
            
            # Create directory if it doesn't exist
            sudo mkdir -p $DEPLOY_DIR
            
            # Extract new files
            sudo tar -xzf /tmp/static-resume.tar.gz -C $DEPLOY_DIR
            
            # Set proper permissions
            sudo chown -R apache:apache $DEPLOY_DIR
            sudo chmod -R 755 $DEPLOY_DIR
            
            # Start Apache
            sudo systemctl start httpd
            
            # Verify Apache is running
            sudo systemctl status httpd --no-pager
            
            echo "Dev deployment to $DEPLOY_DIR complete. Apache restarted."
          EOF