name: Deploy Static Resume to AWS EC2 via Docker

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/static-resume
  DEV_SERVER: ${{ secrets.DEV_SERVER_IP }}
  PROD_SERVER: ${{ secrets.PROD_SERVER_IP }}

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.tag }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set image tag using short SHA
        id: set_tag
        run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ steps.set_tag.outputs.tag }} .

      - name: Push Docker images
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ steps.set_tag.outputs.tag }}

  deploy-dev:
    name: Deploy to Development EC2
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Debug tag and image
        run: |
          echo "Tag: ${{ needs.build-and-push.outputs.image_tag }}"
          echo "Image: ${{ env.IMAGE_NAME }}"

      - name: Copy and execute deploy script on Dev EC2
        run: |
          TAG=${{ needs.build-and-push.outputs.image_tag }}
          IMAGE_NAME=${{ env.IMAGE_NAME }}
          scp -o StrictHostKeyChecking=no ./deploy-container.sh ec2-user@${{ env.DEV_SERVER }}:/tmp/
          ssh -o StrictHostKeyChecking=no ec2-user@${{ env.DEV_SERVER }} \
            "chmod +x /tmp/deploy-container.sh && /tmp/deploy-container.sh $IMAGE_NAME $TAG development 8080"

  deploy-prod:
    name: Deploy to Production EC2
    needs: [deploy-dev, build-and-push]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Debug tag and image
        run: |
          echo "Tag: ${{ needs.build-and-push.outputs.image_tag }}"
          echo "Image: ${{ env.IMAGE_NAME }}"

      - name: Copy and execute deploy script on Prod EC2
        run: |
          TAG=${{ needs.build-and-push.outputs.image_tag }}
          IMAGE_NAME=${{ env.IMAGE_NAME }}
          scp -o StrictHostKeyChecking=no ./deploy-container.sh ec2-user@${{ env.PROD_SERVER }}:/tmp/
          ssh -o StrictHostKeyChecking=no ec2-user@${{ env.PROD_SERVER }} \
            "chmod +x /tmp/deploy-container.sh && /tmp/deploy-container.sh $IMAGE_NAME $TAG production 8080"
