name: Deploy Static Resume

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  DEPLOY_DIR: "/var/www/html"

jobs:
  build:
    name: Package Site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: site-build
          path: ./

  deploy:
    name: Deploy to Server
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: 
          - name: dev
            server: ${{ secrets.DEV_SERVER_IP }}
          - name: prod
            server: ${{ secrets.PROD_SERVER_IP }}
            if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: site-build
          path: build/

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to ${{ matrix.environment.name }}
        run: |
          # Package and transfer files
          tar -czf site.tar.gz -C build/ .
          scp -o StrictHostKeyChecking=no site.tar.gz ec2-user@${{ matrix.environment.server }}:/tmp/

          # Remote deployment commands
          ssh -o StrictHostKeyChecking=no ec2-user@${{ matrix.environment.server }} << 'EOF'
            set -e
            echo "Starting deployment to $DEPLOY_DIR"

            # Ensure Apache is ready
            sudo dnf install -y httpd || true
            sudo systemctl stop httpd || true
            sudo pkill httpd || true
            sudo fuser -k 80/tcp || true

            # Clean and prepare directory
            sudo rm -rf $DEPLOY_DIR/*
            sudo mkdir -p $DEPLOY_DIR
            sudo tar -xzf /tmp/site.tar.gz -C $DEPLOY_DIR

            # Set permissions
            sudo chown -R apache:apache $DEPLOY_DIR
            sudo chmod -R 755 $DEPLOY_DIR
            sudo restorecon -Rv $DEPLOY_DIR || true

            # Start Apache
            sudo systemctl start httpd
            sudo systemctl status httpd --no-pager

            echo "Deployment to ${{ matrix.environment.name }} complete"
          EOF