name: Deploy Static Resume to AWS EC2

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  APP_NAME: "static-resume"
  DEV_SERVER: ${{ secrets.DEV_SERVER_IP }}
  PROD_SERVER: ${{ secrets.PROD_SERVER_IP }}

jobs:
  build:
    name: Prepare Static Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload HTML files
        uses: actions/upload-artifact@v4
        with:
          name: static-resume-build
          path: ./

  deploy-dev:
    name: Deploy to Development EC2
    needs: build
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: static-resume-build
          path: build/

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Dev EC2
        run: |
          scp -r -o StrictHostKeyChecking=no build/* ec2-user@${{ env.DEV_SERVER }}:/tmp/static-resume/
          ssh -o StrictHostKeyChecking=no ec2-user@${{ env.DEV_SERVER }} << 'EOF'
            set -ex
            DEPLOY_DIR="/var/www/html"

            if ! command -v httpd &>/dev/null; then
              sudo dnf install -y httpd
              sudo systemctl enable httpd
            fi

            sudo systemctl stop httpd || true
            sudo fuser -k 80/tcp || true
            sudo rm -rf $DEPLOY_DIR/*
            sudo cp -r /tmp/static-resume/* $DEPLOY_DIR/
            sudo chown -R apache:apache $DEPLOY_DIR
            sudo chmod -R 755 $DEPLOY_DIR

            if command -v sestatus &>/dev/null && sudo sestatus | grep -q enabled; then
              sudo restorecon -Rv $DEPLOY_DIR
            fi

            sudo apachectl configtest
            sudo systemctl start httpd
            echo "Dev deployment complete"
          EOF

  deploy-prod:
    name: Deploy to Production EC2
    needs: deploy-dev
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: static-resume-build
          path: build/

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Prod EC2
        run: |
          scp -r -o StrictHostKeyChecking=no build/* ec2-user@${{ env.PROD_SERVER }}:/tmp/static-resume/
          ssh -o StrictHostKeyChecking=no ec2-user@${{ env.PROD_SERVER }} << 'EOF'
            set -ex
            DEPLOY_DIR="/var/www/html"

            if ! command -v httpd &>/dev/null; then
              sudo dnf install -y httpd
              sudo systemctl enable httpd
            fi

            sudo systemctl stop httpd || true
            sudo fuser -k 80/tcp || true
            sudo rm -rf $DEPLOY_DIR/*
            sudo cp -r /tmp/static-resume/* $DEPLOY_DIR/
            sudo chown -R apache:apache $DEPLOY_DIR
            sudo chmod -R 755 $DEPLOY_DIR

            if command -v sestatus &>/dev/null && sudo sestatus | grep -q enabled; then
              sudo restorecon -Rv $DEPLOY_DIR
            fi

            sudo apachectl configtest
            sudo systemctl start httpd
            curl -I http://localhost || true
            echo "Production deployment complete"
          EOF
