jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync and prepare on Dev EC2
        run: |
          rsync -av --delete \
            --exclude='.github' \
            "$GITHUB_WORKSPACE"/ ec2-user@${{ secrets.DEV_SERVER_IP }}:/var/www/html/

      - name: Fix perms & restart webserver on Dev
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.DEV_SERVER_IP }} << 'EOF'
            # Ensure directory exists and has correct ownership
            sudo mkdir -p /var/www/html
            sudo chown -R ec2-user:ec2-user /var/www/html

            # Final perms and restart
            sudo chown -R apache:apache /var/www/html
            sudo chmod -R 755 /var/www/html

            if systemctl is-active --quiet httpd; then
              sudo systemctl restart httpd
            elif systemctl is-active --quiet apache2; then
              sudo systemctl restart apache2
            else
              echo "No httpd/apache2 service found"
            fi
          EOF

  deploy-prod:
    needs: deploy-dev
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync and prepare on Prod EC2
        run: |
          rsync -av --delete \
            --exclude='.github' \
            "$GITHUB_WORKSPACE"/ ec2-user@${{ secrets.PROD_SERVER_IP }}:/var/www/html/

      - name: Fix perms & restart webserver on Prod
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.PROD_SERVER_IP }} << 'EOF'
            sudo mkdir -p /var/www/html
            sudo chown -R ec2-user:ec2-user /var/www/html

            sudo chown -R apache:apache /var/www/html
            sudo chmod -R 755 /var/www/html

            if systemctl is-active --quiet httpd; then
              sudo systemctl restart httpd
            elif systemctl is-active --quiet apache2; then
              sudo systemctl restart apache2
            else
              echo "No httpd/apache2 service found"
            fi
          EOF
